name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build and Publish
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
        run: |
          echo "[pypi]" > ~/.config/pypoetry/config.toml
          echo "token = '$POETRY_PYPI_TOKEN'" >> ~/.config/pypoetry/config.toml
          poetry build
          poetry publish --build # Remove -n flag for actual publishing
